


export const GET_MOVIES_START='GET_MOVIES_START'
export const GET_MOVIES_SUCCESS='GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILED='GET_MOVIES_FAILED'
export const GET_MOVIE_START='GET_MOVIE_START'
export const GET_MOVIE_SUCCESS='GET_MOVIE_SUCCESS'
export const GET_MOVIE_FAILED='GET_MOVIE_FAILED'